[tool.bumpversion]
current_version = "0.41.1.dev0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(\\.dev(?P<dev>\\d+))?"
serialize = ["{major}.{minor}.{patch}.dev{dev}"]

[[tool.bumpversion.files]]
filename = "src/atlas4py/_version.py"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
